### ISSUE TITLE
Incompatibility with miniconda role

### ISSUE THREAD

**Issue by akorosov** [andrewrothstein/ansible-conda-env#4]
This is a very useful role! Thank you, @andrewrothstein !
I was struggling to make it work before I realized I should play your miniconda role first.
Maybe it can be added as a dependency?

The miniconda role forces the conda diretory to be owned by root. And  when I run conda-env and specify `conda_env_escalate: False` it refuses to install packages.

**Comment by andrewrothstein** [comment]
Sorry for the confusion. Anaconda and Miniconda installations are user rather than system scoped. Both my anaconda and miniconda roles install the respective software as the root user. I never listed either as a dependency because I want to be able to use this role with both/either of those roles. I'm open to the idea of making those roles (ansible-anaconda and ansible-miniconda) optionally less root user oriented so that this role can be used with them when ```conda_env_escalate: False```.
